{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pizza_creation_latency_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza service dev",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "latency_milliseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "Total Requests" },
    { "expr": "post_requests_total", "legendFormat": "__auto" },
    { "expr": "get_requests_total", "legendFormat": "__auto" },
    { "expr": "delete_requests_total", "legendFormat": "__auto" },
    { "expr": "put_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentications attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "rate(auth_success_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(auth_failed_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizza_creation_failures_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "rate(pizzas_sold_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "active_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" },
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}